main: nl.dantevg.webstats.WebStats
name: WebStats
version: ${version} # Filled in automatically by maven
api-version: 1.13
description: Display the scoreboard, PlaceholderAPI and other plugin statistics on the web
author: RedPolygon
website: dantevg.nl/mods-plugins/WebStats
softdepend: [Essentials, PlaceholderAPI, SkinsRestorer]
commands:
  webstats:
    description: WebStats command
    usage: |
      Usage:
        /<command> debug
        /<command> reload
        /<command> export
        /<command> migrate-placeholders-to (database | csv)
        /<command> delete-placeholders <player>
    permission: webstats.*
permissions:
  webstats.*:
    description: Allows running /webstats command
