main: nl.dantevg.webstats.Main
name: WebStats
version: 1.4
api-version: 1.16
description: Display the scoreboard, PlaceholderAPI and other plugin statistics on the web
author: RedPolygon
website: dantevg.nl/mods-plugins/WebStats
softdepend: [Essentials, PlaceholderAPI]
