main: nl.dantevg.webstats.Main
name: WebStats
version: 1.2.2
description: Exposes the scoreboard and other statistics to the web
author: RedPolygon
website: dantevg.nl/mods-plugins/WebStats
softdepend: [Essentials]