main: nl.dantevg.webstats.Main
name: WebStats
version: 1.3.2
description: View the scoreboard and player online status on the web
author: RedPolygon
website: dantevg.nl/mods-plugins/WebStats
softdepend: [Essentials, PlaceholderAPI]
