# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  node:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: 'web/package-lock.json'
    - run: npm ci
      working-directory: web
    - name: Cache js file
      uses: actions/cache@v3
      with:
        path: web/WebStats-dist.js
        key: js

  maven:

    runs-on: ubuntu-latest

    needs: node

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Get cached js file
      uses: actions/cache/restore@v3
      with:
        path: web/WebStats-dist.js
        key: js
        fail-on-cache-miss: true
    - name: Copy js file to out directory and jar resources
      run: mkdir out && cp web/WebStats-dist.js out && cp web/WebStats-dist.js* src/main/resources/web
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3
    - name: Get latest commit hash (push)
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        echo "LAST_COMMIT_SHA=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV
    - name: Get latest commit hash (pull request)
      if: ${{ github.event_name == 'push' }}
      run: |
        echo "LAST_COMMIT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
    - name: Copy jar to out directory
      run: cp target/WebStats-*.jar out/WebStats-${{ github.head_ref || github.ref_name }}-${{ env.LAST_COMMIT_SHA }}.jar
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: WebStats
        path: out
